language: node_js
node_js:
  - 14.16.0
branches:
  only:
    - master
cache:
  directories:
    - node_modules

before_install:
  - npm install -g yarn
  - cd ./frontend
  - openssl aes-256-cbc -K $encrypted_538818e76846_key -iv $encrypted_538818e76846_iv -in .env.production.enc -out .env.production -d

script: yarn build
notifications:
  email:
    recipients:
      - kwag93@naver.com

deploy:
  provider: s3
  access_key_id: $AWSACCESSKEY
  secret_access_key: $AWSSECRETKEY
  bucket: 42chelin
  skip_cleanup: true
  acl: public_read
  region: ap-northeast-2
  wait-until-deploy: true
  local_dir: build
